spring.application.name=fit-core-api
# 기본 프로파일 (없애도 됨)
spring.profiles.active=local
# 공통 설정
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
# sql.init는 Flyway가 대체 — 전 환경 비활성화
spring.sql.init.mode=never
# Flyway (스키마 형상 관리)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true